" auto install plug
if empty(glob('~/.vim/autoload/plug.vim'))
      silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
          \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')
Plug 'cresny/vim-code-dark'
Plug 'sjl/gundo.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'fatih/vim-go', { 'for':'go'}
Plug 'JamshedVesuna/vim-markdown-preview'
call plug#end()

set t_Co=256
set t_ut= 

colorscheme codedark
"colorscheme desert

syntax enable

set tabstop=4

set softtabstop=4

set shiftwidth=4

set expandtab

set mouse=a

set relativenumber

" necessary for delete key backwards delete
set backspace=2

filetype indent on
filetype plugin on

set number

" show choices for autocompletion when opening files
set wildmenu

let mapleader=","

"enable subfolder search
set path+=**

" toggle gundo
nnoremap <leader>u :GundoToggle<CR>


set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>


" Go command key bindings
autocmd FileType go nmap <leader>b  <Plug>(go-build)
autocmd FileType go nmap <leader>r  <Plug>(go-run)

set autowrite

autocmd FileType go nmap <C-n> :cnext<CR>
autocmd FileType go nmap <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>

" turn off backup, swap, etc. I sometimes open up more thank one session and
" it adds confusion. Also we have git!
set nobackup
set nowb
set noswapfile

" Golang json macro -- use @j over struct field to add lcase json tag
let @j='yiw/$a `json:"p?"€kr~/$a"`'

let vim_markdown_preview_browser='Google Chrome'
let vim_markdown_preview_github=1

vnoremap <C-c> "*y    
